// directory-hints.js
// ---------------------------------------------------------------------------
// Paths on label/certification sites that are LIKELY to list brands, members,
// certified companies, partners, licensees, retailers, or a searchable registry.
// Keep EVERYTHING lowercase. Prefer generic path segments, not full URLs.
// Expand freely as you encounter new patterns in the wild.
// ---------------------------------------------------------------------------

export default [
	// Core English
	"/brands",
	"/our-brands",
	"/brand",
	"/brand-list",
	"/brand-directory",
	"/brand-index",
	"/brands-a-z",
	"/a-z-brands",
	"/companies",
	"/company",
	"/company-list",
	"/company-directory",
	"/members",
	"/membership",
	"/member",
	"/member-list",
	"/member-directory",
	"/partners",
	"/partner",
	"/partner-list",
	"/partner-directory",
	"/licensee",
	"/licensees",
	"/licensee-list",
	"/licensee-directory",
	"/license-holders",
	"/license-holder-list",
	"/certified",
	"/certified-companies",
	"/certified-brands",
	"/certifications",
	"/certificate-holders",
	"/approved",
	"/approved-brands",
	"/approved-companies",
	"/listed",
	"/listed-companies",
	"/registry",
	"/register",
	"/registration-list",
	"/database",
	"/directory",
	"/directories",
	"/list",
	"/lists",
	"/finder",
	"/product-finder",
	"/brand-finder",
	"/company-finder",
	"/buyers-guide",
	"/where-to-buy",
	"/retailers",
	"/stockists",
	"/vendors",
	"/suppliers",
	"/manufacturer",
	"/manufacturers",
	"/manufacturers-list",
	"/distributors",
	"/distributor-list",
	"/marketplace",
	"/catalog",
	"/catalogue",
	"/search",
	"/search-results",
	"/results",
	"/explore",
	"/network",
	"/ecosystem",

	// Common CMS/collection slugs
	"/collections/brands",
	"/collections/members",
	"/collections/partners",
	"/collections/certified",
	"/collection/brands",
	"/collection/companies",

	// Region / category variations
	"/brands/international",
	"/brands/global",
	"/brands/local",
	"/brands/regional",
	"/members/global",
	"/members/regional",
	"/members/local",
	"/directory/global",
	"/directory/regional",

	// Additional pluralization / wordings
	"/brand-partners",
	"/brand-members",
	"/brand-owners",
	"/brand-owners-list",
	"/brand-owners-directory",
	"/brand-licensees",
	"/brand-license-holders",
	"/company-partners",
	"/company-members",
	"/company-register",
	"/company-registry",
	"/company-index",
	"/member-index",
	"/partner-index",
	"/licensee-index",
	"/supplier-directory",
	"/supplier-list",
	"/vendor-directory",
	"/vendor-list",
	"/retailer-directory",
	"/retailer-list",
	"/stockist-directory",
	"/stockist-list",
	"/manufacturer-directory",
	"/manufacturer-list",
	"/distributor-directory",
	"/distributor-list",

	// Certification-ish phrasing
	"/certified/list",
	"/certified/directory",
	"/certified/companies",
	"/certified/members",
	"/certified/brands",
	"/certification/holders",
	"/certification/licensees",
	"/certification/registry",
	"/program/participants",
	"/program/partners",
	"/program/members",
	"/program/licensees",

	// “Who we work with” variants
	"/who-we-work-with",
	"/who-we-certify",
	"/who-we-approve",
	"/who-we-list",
	"/who-we-partner-with",
	"/our-members",
	"/our-partners",
	"/our-brands",
	"/our-licensees",
	"/our-network",

	// “Find …” / “Look up …”
	"/find-a-brand",
	"/find-a-company",
	"/find-a-member",
	"/find-a-retailer",
	"/find-a-supplier",
	"/find-a-licensee",
	"/find-an-organization",
	"/brand-search",
	"/company-search",
	"/member-search",
	"/supplier-search",

	// B2B-ish
	"/buyers",
	"/buyers/guide",
	"/buyers/list",
	"/buyers/directory",
	"/procurement/approved-suppliers",
	"/procurement/suppliers",
	"/procurement/vendors",

	// Multi-language HINTS (very common in EU/LatAm/Asia sites)
	// Spanish
	"/marcas",
	"/nuestras-marcas",
	"/empresas",
	"/empresas-certificadas",
	"/socios",
	"/miembros",
	"/directorio",
	"/proveedores",
	"/distribuidores",
	"/minoristas",
	"/donde-comprar",
	"/buscador",
	"/registro",
	"/licenciatarios",
	// French
	"/marques",
	"/nos-marques",
	"/entreprises",
	"/entreprises-certifiees",
	"/partenaires",
	"/membres",
	"/annuaire",
	"/fournisseurs",
	"/distributeurs",
	"/revendeurs",
	"/ou-acheter",
	"/recherche",
	"/registre",
	"/titulaire-de-licence",
	"/licencies",
	// German
	"/marken",
	"/unsere-marken",
	"/unternehmen",
	"/zertifizierte-unternehmen",
	"/partner",
	"/mitglieder",
	"/verzeichnis",
	"/lieferanten",
	"/vertriebspartner",
	"/haendler",
	"/haendlerverzeichnis",
	"/wo-kaufen",
	"/suche",
	"/register",
	"/lizenznehmer",
	// Italian
	"/marchi",
	"/i-nostri-marchi",
	"/aziende",
	"/aziende-certificate",
	"/partner",
	"/membri",
	"/elenco",
	"/fornitori",
	"/distributori",
	"/rivenditori",
	"/dove-acquistare",
	"/ricerca",
	"/registro",
	"/licenziatari",
	// Portuguese
	"/marcas",
	"/nossas-marcas",
	"/empresas",
	"/empresas-certificadas",
	"/parceiros",
	"/membros",
	"/diretorio",
	"/fornecedores",
	"/distribuidores",
	"/revendedores",
	"/onde-comprar",
	"/busca",
	"/registro",
	"/licenciados",
	// Dutch
	"/merken",
	"/onze-merken",
	"/bedrijven",
	"/gecertificeerde-bedrijven",
	"/partners",
	"/leden",
	"/register",
	"/leveranciers",
	"/distributeurs",
	"/retailers",
	"/waar-te-kopen",
	"/zoeken",
	"/gids",
	// Swedish / Danish / Norwegian variants
	"/varumarken",
	"/vara-varumarken",
	"/foretag",
	"/certifierade-foretag",
	"/partner",
	"/medlemmar",
	"/katalog",
	"/leverantorer",
	"/aterforsaljare",
	"/var-kopa",
	"/sok",
	"/register",
	"/licenstagare",
	"/mærker",
	"/vores-mærker",
	"/virksomheder",
	"/certificerede-virksomheder",
	"/partnere",
	"/medlemmer",
	"/leverandorer",
	"/forhandlere",
	"/hvor-kan-man-kobe",
	"/sog",
	"/register",
	// Finnish
	"/tuotemerkit",
	"/yritykset",
	"/sertifioidut-yritykset",
	"/kumppanit",
	"/jasenet",
	"/toimittajat",
	"/jalleenmyyjat",
	"/mista-ostaa",
	"/haku",
	"/rekisteri",
	"/lisenssinsaajat",
	// Polish
	"/marki",
	"/nasze-marki",
	"/firmy",
	"/certyfikowane-firmy",
	"/partnerzy",
	"/czlonkowie",
	"/katalog",
	"/dostawcy",
	"/dystrybutorzy",
	"/sprzedawcy",
	"/gdzie-kupic",
	"/wyszukiwarka",
	"/rejestr",
	"/licencjobiorcy",

	// Asia (selection; helps a ton on JP/KR/CN sites that also expose Latin slugs)
	"/brands-ja",
	"/companies-ja",
	"/members-ja",
	"/partners-ja",
	"/registry-ja",
	"/brands-zh",
	"/companies-zh",
	"/members-zh",
	"/partners-zh",
	"/registry-zh",
	"/brands-ko",
	"/companies-ko",
	"/members-ko",
	"/partners-ko",
	"/registry-ko",

	// Edge phrasing we’ve seen in the wild
	"/accredited-companies",
	"/accredited-members",
	"/recognized-brands",
	"/endorsed-brands",
	"/authorized-brands",
	"/authorized-partners",
	"/program-participants",
	"/participant-directory",
	"/member-companies",
	"/member-brands",
	"/brand-owners",
	"/brand-owners-directory",
	"/company-index",
	"/brand-index",
	"/alpha-list",
	"/az-list",
	"/a-z",
	"/zertifiziert", // de “certified”
	"/liste", // fr/it “list”
	"/elenco", // it “list”
	"/registro-empresas", // es/pt
	"/registro-marcas", // es/pt
	"/registre", // fr
	"/registre-des-entreprises", // fr
	"/marcas-certificadas", // es/pt
	"/entreprises-agrees", // fr “approved companies”
];
