// negative-terms.js
// ---------------------------------------------------------------------------
// Obvious junk strings to drop BEFORE scoring/extraction.
// - Keep EVERYTHING lowercase (run.js lowercases before matching).
// - Full-string matches only (post-normalization), not substring.
// - Add new junk here anytime you see leakage in company candidates.
// ---------------------------------------------------------------------------

export default [
	// Core chrome / boilerplate
	"home",
	"start",
	"welcome",
	"dashboard",
	"menu",
	"main menu",
	"user menu",
	"navigation",
	"nav",
	"breadcrumb",
	"breadcrumbs",
	"sitemap",
	"site map",
	"header",
	"footer",
	"sidebar",
	"aside",
	"toolbar",
	"top bar",
	"status bar",

	// Auth / account / portal
	"login",
	"log in",
	"logout",
	"log out",
	"signin",
	"sign in",
	"signup",
	"sign up",
	"register",
	"registration",
	"account",
	"my account",
	"profile",
	"my profile",
	"admin",
	"admin portal",
	"customer portal",
	"backoffice",
	"control panel",

	// Actions / CTAs
	"search",
	"advanced search",
	"quick search",
	"results",
	"view all",
	"view more",
	"see all",
	"browse all",
	"explore",
	"discover",
	"download",
	"downloads",
	"upload",
	"uploads",
	"share",
	"print",
	"apply",
	"submit",
	"continue",
	"reset",
	"filter",
	"sort",

	// About / org info
	"about",
	"about us",
	"our story",
	"who we are",
	"what we do",
	"mission",
	"vision",
	"values",
	"ethos",
	"history",
	"background",
	"overview",
	"highlights",
	"insights",
	"snapshots",
	"statistics",
	"facts",
	"faq",
	"faqs",
	"help",
	"support",

	// Legal / compliance
	"privacy",
	"privacy policy",
	"cookie",
	"cookies",
	"cookie policy",
	"terms",
	"terms of use",
	"terms & conditions",
	"legal",
	"imprint",
	"impressum",
	"disclaimer",
	"gdpr",
	"ccpa",
	"accessibility",
	"accessibility statement",
	"security",
	"code of conduct",
	"ethics",
	"anti-bribery",
	"modern slavery",

	// Comms / media
	"press",
	"pressroom",
	"newsroom",
	"media",
	"news",
	"updates",
	"announcements",
	"stories",
	"blog",
	"blogs",
	"articles",
	"events",
	"event",
	"webinars",
	"workshops",
	"newsletter",
	"subscribe",
	"rss",
	"feed",
	"social",
	"share",
	"follow us",

	// Careers / people
	"careers",
	"jobs",
	"vacancies",
	"open positions",
	"opportunities",
	"team",
	"our team",
	"leadership",
	"management",
	"board",
	"advisors",
	"members",
	"membership",
	"community",
	"partners",
	"sponsors",
	"donors",

	// Commerce / directory wrappers (not org names)
	"marketplace",
	"store",
	"stores",
	"shop",
	"shops",
	"catalog",
	"catalogs",
	"catalogue",
	"catalogues",
	"listing",
	"listings",
	"directory",
	"directories",
	"index",
	"indices",
	"registry",
	"register",
	"where to buy",
	"buyers guide",
	"retailers",
	"stockists",
	"suppliers",
	"distributors",
	"vendors",
	"dealers",

	// Help / contact
	"help center",
	"contact",
	"contact us",
	"get in touch",
	"customer service",
	"feedback",
	"knowledge base",
	"docs",
	"documentation",
	"resources",
	"resource",

	// E-commerce ops
	"cart",
	"basket",
	"checkout",
	"order",
	"orders",
	"payments",
	"payment",
	"billing",
	"invoice",
	"invoices",
	"quote",
	"quotes",

	// Explicit junk phrases we saw in your dataset
	"access to this site",
	"access to the product portal",
	"about our certification services",
	"about the ecolabel",
	"about usgbc",
	"document centre files",
	"documents",
	"document",
	"discrimination",
	"dollar amount",
	"dishwasher detergents", // category, not a brand
	"accessibility",

	// Boilerplate footers
	"copyright",
	"all rights reserved",
	"trademark",

	// Misc generic
	"more",
	"next",
	"previous",
	"prev",
	"back",
	"read more",
	"learn more",
];
