// bad-plurals.js
// ---------------------------------------------------------------------------
// Plural/category words that commonly appear as headings, filters, menus,
// or product group labels — not company/brand names. Keep EVERYTHING lowercase.
// Add more as you encounter junk slipping through.
// ---------------------------------------------------------------------------

export default [
	// Admin / menu-y
	"abouts",
	"accounts",
	"dashboards",
	"uploads",
	"downloads",
	"bookmarks",
	"shortcuts",
	"favorites",
	"favourites",
	"breadcrumbs",
	"settings",
	"notifications",
	"alerts",
	"banners",
	"sections",
	"menus",
	"submenus",
	"tabs",
	"widgets",
	"footers",
	"headers",
	"sidebars",
	"filters",
	"facets",
	"options",
	"preferences",

	// Docs / legal / governance
	"documents",
	"files",
	"attachments",
	"appendices",
	"annexes",
	"records",
	"logs",
	"reports",
	"statements",
	"disclosures",
	"policies",
	"procedures",
	"guidelines",
	"standards",
	"requirements",
	"terms",
	"conditions",
	"licenses",
	"licences",
	"agreements",
	"contracts",
	"notices",
	"disclaimers",
	"faqs",
	"minutes",
	"bylaws",
	"charters",
	"forms",
	"applications",
	"requests",
	"checklists",
	"templates",
	"roadmaps",
	"briefs",
	"whitepapers",
	"handbooks",
	"manuals",

	// Org / people / pages
	"teams",
	"members",
	"staff",
	"employees",
	"volunteers",
	"advisors",
	"directors",
	"leaders",
	"partners",
	"sponsors",
	"donors",
	"investors",
	"shareholders",
	"stakeholders",
	"alumni",
	"ambassadors",
	"mentors",
	"interns",
	"contractors",

	// Site structure / comms
	"press",
	"news",
	"articles",
	"blogs",
	"posts",
	"stories",
	"features",
	"highlights",
	"events",
	"webinars",
	"workshops",
	"trainings",
	"courses",
	"classes",
	"programs",
	"projects",
	"initiatives",
	"campaigns",
	"announcements",
	"updates",
	"releases",

	// Commerce / directory-ish
	"retailers",
	"stockists",
	"wholesalers",
	"distributors",
	"suppliers",
	"vendors",
	"resellers",
	"dealers",
	"marketplaces",
	"catalogs",
	"catalogues",
	"listings",
	"directories",
	"indexes",
	"indices",
	"registries",
	"registers",
	"portfolios",

	// Tech / product generic
	"products",
	"solutions",
	"services",
	"platforms",
	"tools",
	"utilities",
	"features",
	"integrations",
	"endpoints",
	"interfaces",
	"dashboards",
	"analytics",
	"insights",
	"pipelines",
	"datasets",
	"workflows",
	"automations",
	"backups",
	"releases",
	"versions",
	"patches",
	"tickets",
	"incidents",
	"outages",
	"deployments",

	// Commerce attributes
	"prices",
	"discounts",
	"coupons",
	"vouchers",
	"offers",
	"bundles",
	"skus",
	"orders",
	"shipments",
	"deliveries",
	"returns",
	"refunds",
	"exchanges",
	"inventories",
	"warehouses",
	"stores",
	"locations",
	"branches",

	// CSR / ESG / generic nouns that leak a lot
	"impacts",
	"initiatives",
	"pillars",
	"commitments",
	"pledges",
	"audits",
	"assessments",
	"certifications",
	"accreditations",
	"verifications",
	"auditees",
	"ratings",
	"rankings",
	"benchmarks",
	"indices",
	"goals",
	"targets",
	"milestones",

	// Support / help
	"helps",
	"supports",
	"tutorials",
	"guides",
	"handbooks",
	"manuals",
	"how-tos",
	"troubleshootings",
	"resolutions",
	"tickets",
	"cases",
	"requests",

	// Finance / admin nouns
	"budgets",
	"invoices",
	"statements",
	"balances",
	"ledgers",
	"audits",
	"payments",
	"payouts",
	"purchases",
	"expenses",
	"revenues",
	"earnings",
	"dividends",

	// Policy-ish
	"privacies",
	"cookies",
	"preferences",
	"consents",
	"permissions",
	"restrictions",
	"prohibitions",
	"exemptions",
	"waivers",

	// Product categories — FMCG / household / cosmetics (frequent leaks)
	"detergents",
	"disinfectants",
	"cleaners",
	"wipes",
	"sanitizers",
	"degreasers",
	"fragrances",
	"perfumes",
	"colognes",
	"deodorants",
	"conditioners",
	"shampoos",
	"soaps",
	"lotions",
	"creams",
	"serums",
	"oils",
	"butters",
	"balms",
	"toners",
	"exfoliants",
	"scrubs",
	"masks",
	"peels",
	"sunscreens",
	"moisturizers",
	"toothpastes",
	"mouthwashes",
	"detergents",
	"softeners",
	"bleaches",
	"stain-removers",
	"dishwashers",
	"dishwashing-liquids",
	"rinses",
	"polishes",
	"fresheners",
	"deodorizers",

	// Food / beverage categories
	"snacks",
	"beverages",
	"drinks",
	"juices",
	"teas",
	"coffees",
	"sauces",
	"condiments",
	"seasonings",
	"spices",
	"sweeteners",
	"cereals",
	"grains",
	"breads",
	"pastries",
	"desserts",
	"yogurts",
	"dairies",
	"cheeses",
	"meats",
	"seafoods",
	"fruits",
	"vegetables",

	// Apparel / retail categories
	"accessories",
	"apparels",
	"footwears",
	"sneakers",
	"boots",
	"sandals",
	"jackets",
	"shirts",
	"trousers",
	"jeans",
	"hoodies",
	"sweaters",
	"socks",
	"underwears",
	"bags",
	"backpacks",
	"wallets",
	"belts",
	"hats",
	"gloves",
	"scarves",

	// Hardware / devices
	"devices",
	"appliances",
	"machines",
	"engines",
	"motors",
	"components",
	"spares",
	"parts",
	"modules",
	"kits",
	"accessories",
	"consumables",

	// Materials
	"plastics",
	"papers",
	"metals",
	"alloys",
	"textiles",
	"fabrics",
	"fibers",
	"woods",
	"timbers",
	"glasses",
	"ceramics",
	"composites",
	"adhesives",
	"coatings",
	"paints",
	"inks",
	"dyes",
	"solvents",
	"lubricants",
	"resins",
	"polymers",

	// Healthcare / safety
	"medicines",
	"drugs",
	"supplements",
	"vitamins",
	"first-aids",
	"bandages",
	"gloves",
	"masks",
	"respirators",
	"sanitizers",
	"disposables",
	"equipments",

	// Random generic plurals that often leak
	"opens",
	"closings",
	"winners",
	"winners-list",
	"runners",
	"learners",
	"providers",
	"solutions-providers",
	"resources",
	"toolkits",
	"toolboxes",
	"playbooks",
	"case-studies",
	"use-cases",
	"showcases",
	"highlights",
	"snapshots",
	"galleries",
	"carousels",
	"banners",
	"tiles",
	"cards",
	"blocks",

	// Language / accessibility / portal junk
	"accessibilities",
	"translations",
	"languages",
	"localizations",
	"alt-texts",
	"subtitles",
	"captions",
	"transcripts",
	"portals",
	"gateways",
	"hubs",

	// Careers / HR
	"careers",
	"jobs",
	"vacancies",
	"openings",
	"positions",
	"opportunities",
	"benefits",
	"perks",
	"holidays",
	"policies",
	"handbooks",
];
