// generic-nouns.js
// ---------------------------------------------------------------------------
// Generic nouns / headings / menu labels that frequently appear on pages but
// are NOT company/brand names. Keep everything LOWERCASE. Add as you discover
// more junk leaking into results. This list feeds a Set() and is matched as
// full-string equality after normalization.
// ---------------------------------------------------------------------------

export default [
	// --- Site chrome / navigation ---
	"home",
	"start",
	"welcome",
	"dashboard",
	"menu",
	"main menu",
	"user menu",
	"navigation",
	"nav",
	"breadcrumb",
	"breadcrumbs",
	"sitemap",
	"site map",
	"header",
	"footer",
	"sidebar",
	"aside",
	"toolbar",
	"top bar",
	"status bar",

	// --- Account / auth / portals ---
	"account",
	"my account",
	"accounts",
	"profile",
	"my profile",
	"login",
	"log in",
	"logout",
	"log out",
	"sign in",
	"sign out",
	"signup",
	"sign up",
	"register",
	"registration",
	"portal",
	"customer portal",
	"admin",
	"admin portal",
	"backoffice",
	"back office",
	"my dashboard",
	"control panel",

	// --- Search / filters / actions ---
	"search",
	"advanced search",
	"quick search",
	"global search",
	"filters",
	"filter",
	"facets",
	"sort",
	"sort by",
	"results",
	"view all",
	"see all",
	"browse all",
	"explore",
	"discover",
	"download",
	"downloads",
	"upload",
	"uploads",
	"share",
	"print",

	// --- About / info pages ---
	"about",
	"about us",
	"our story",
	"who we are",
	"what we do",
	"mission",
	"vision",
	"values",
	"ethos",
	"history",
	"background",
	"overview",
	"highlights",
	"insights",
	"snapshots",
	"statistics",
	"facts",
	"faq",
	"faqs",
	"help",
	"support",

	// --- Contact / communications ---
	"contact",
	"contact us",
	"get in touch",
	"feedback",
	"inquiries",
	"enquiries",
	"press",
	"media",
	"news",
	"newsroom",
	"updates",
	"announcements",
	"stories",
	"blog",
	"blogs",
	"articles",
	"events",
	"webinars",
	"workshops",
	"newsletter",

	// --- Legal / compliance ---
	"privacy",
	"privacy policy",
	"cookie policy",
	"cookies",
	"terms",
	"terms of use",
	"terms and conditions",
	"legal",
	"imprint",
	"disclaimer",
	"gdpr",
	"ccpa",
	"compliance",
	"governance",
	"code of conduct",
	"ethics",
	"anti-bribery",
	"modern slavery",
	"accessibility",
	"accessibility statement",

	// --- Careers / people ---
	"careers",
	"jobs",
	"vacancies",
	"open positions",
	"opportunities",
	"team",
	"our team",
	"leadership",
	"management",
	"board",
	"advisors",
	"partners",
	"sponsors",
	"donors",
	"members",
	"membership",
	"community",

	// --- Program / initiative / generic org nouns ---
	"program",
	"programs",
	"programme",
	"programmes",
	"initiative",
	"initiatives",
	"project",
	"projects",
	"campaign",
	"campaigns",
	"case study",
	"case studies",
	"use cases",
	"resources",
	"library",
	"resource library",
	"toolbox",
	"toolkit",
	"knowledge base",
	"documentation",
	"docs",
	"doc center",
	"document centre files",
	"documents",
	"document",
	"downloads center",

	// --- Reporting / governance nouns ---
	"report",
	"reports",
	"annual report",
	"financial report",
	"impact report",
	"statements",
	"statement",
	"disclosure",
	"disclosures",
	"transparency",
	"policies",
	"policy",
	"guidelines",
	"standards",
	"requirements",
	"procedures",
	"processes",
	"manual",
	"handbook",
	"whitepaper",
	"white paper",

	// --- Commerce / directory wrappers (not org names themselves) ---
	"catalog",
	"catalogue",
	"catalogs",
	"catalogues",
	"listing",
	"listings",
	"directory",
	"directories",
	"index",
	"indices",
	"registry",
	"register",
	"marketplace",
	"store",
	"stores",
	"shop",
	"shops",
	"where to buy",
	"buyers guide",
	"retailers",
	"stockists",
	"suppliers",
	"distributors",
	"vendors",
	"dealers",

	// --- Data / forms / admin nouns ---
	"form",
	"forms",
	"application",
	"applications",
	"apply",
	"request",
	"requests",
	"submissions",
	"submission",
	"feedback form",
	"contact form",
	"dashboard widgets",
	"preferences",
	"settings",
	"notifications",
	"alerts",

	// --- Education / training ---
	"training",
	"trainings",
	"courses",
	"classes",
	"curriculum",
	"modules",
	"lessons",
	"tutorials",
	"how to",
	"guide",
	"guides",
	"handbook",
	"manuals",

	// --- Finance / amounts / misc admin text that leaks as headings ---
	"invoice",
	"invoices",
	"billing",
	"payments",
	"payment",
	"payouts",
	"budget",
	"budgets",
	"expenses",
	"revenues",
	"earnings",
	"balances",
	"dollar amount",
	"amount",
	"totals",
	"summary",
	"overview page",

	// --- Product/category nouns frequently mis-identified as brands ---
	"product",
	"products",
	"solutions",
	"services",
	"features",
	"platform",
	"platforms",
	"integrations",
	"addons",
	"extensions",
	"plugins",
	"tools",
	"utilities",
	"components",
	"modules",
	"kits",
	"parts",

	// --- Household / personal care category nouns (not orgs) ---
	"detergent",
	"detergents",
	"dishwasher detergents",
	"dishwasher",
	"dishwashers",
	"cleaner",
	"cleaners",
	"cleaning",
	"disinfecting",
	"sanitizer",
	"sanitizers",
	"freshener",
	"fresheners",
	"deodorizer",
	"deodorizers",
	"soap",
	"soaps",
	"shampoo",
	"shampoos",
	"conditioner",
	"conditioners",
	"lotion",
	"lotions",
	"cream",
	"creams",
	"serum",
	"serums",
	"oil",
	"oils",
	"toner",
	"toners",
	"mask",
	"masks",
	"peel",
	"peels",
	"scrub",
	"scrubs",

	// --- Food / beverage categories (common filters) ---
	"snack",
	"snacks",
	"beverage",
	"beverages",
	"drink",
	"drinks",
	"juice",
	"juices",
	"tea",
	"teas",
	"coffee",
	"coffees",
	"sauce",
	"sauces",
	"condiment",
	"condiments",
	"seasoning",
	"seasonings",
	"spice",
	"spices",
	"sweetener",
	"sweeteners",
	"cereal",
	"cereals",
	"bread",
	"breads",
	"pastry",
	"pastries",
	"dessert",
	"desserts",
	"yogurt",
	"yogurts",
	"yoghurt",
	"yoghurts",
	"dairy",
	"dairies",
	"cheese",
	"cheeses",
	"meat",
	"meats",
	"seafood",
	"seafoods",
	"fruit",
	"fruits",
	"vegetable",
	"vegetables",

	// --- Apparel / retail category nouns ---
	"apparel",
	"apparels",
	"clothing",
	"clothes",
	"garments",
	"footwear",
	"sneakers",
	"boots",
	"sandals",
	"jackets",
	"shirts",
	"trousers",
	"jeans",
	"hoodies",
	"sweaters",
	"socks",
	"underwear",
	"bags",
	"wallets",
	"belts",
	"hats",
	"gloves",
	"scarves",
	"accessories",

	// --- Materials / industrial nouns ---
	"plastic",
	"plastics",
	"paper",
	"papers",
	"metal",
	"metals",
	"alloy",
	"alloys",
	"textile",
	"textiles",
	"fabric",
	"fabrics",
	"fiber",
	"fibers",
	"wood",
	"woods",
	"timber",
	"timbers",
	"glass",
	"glasses",
	"ceramic",
	"ceramics",
	"composite",
	"composites",
	"adhesive",
	"adhesives",
	"coating",
	"coatings",
	"paint",
	"paints",
	"ink",
	"inks",
	"dye",
	"dyes",
	"solvent",
	"solvents",
	"lubricant",
	"lubricants",
	"resin",
	"resins",
	"polymer",
	"polymers",

	// --- Random meta/UX nouns that appear as grid/card titles ---
	"tile",
	"tiles",
	"card",
	"cards",
	"widget",
	"widgets",
	"carousel",
	"carousels",
	"gallery",
	"galleries",
	"section",
	"sections",
	"tab",
	"tabs",

	// --- Geography / misc headings that are not orgs ---
	"locations",
	"location",
	"branches",
	"offices",
	"office",
	"hq",
	"headquarters",
	"contact details",
	"phone",
	"telephone",
	"fax",
	"email address",

	// --- “About …” + “Access …” style phrases that show up as anchors/headings ---
	"about our certification services",
	"about the ecolabel",
	"about us",
	"about usgbc",
	"about",
	"access to this site",
	"access to the product portal",
	"access",

	// --- Common junk we saw in your dataset ---
	"document centre files",
	"documents",
	"document",
	"discrimination",
	"dollar amount",

	// --- Misc menu junk ---
	"store locator",
	"find a store",
	"find a retailer",
	"find a supplier",
	"work with us",
	"partner with us",
	"get certified",
	"get listed",
	"become a member",
	"become a partner",
	"learn more",
	"read more",

	// --- Catch-all generic wrappers that are definitely not brands ---
	"overview page",
	"landing page",
	"start page",
	"home page",
	"site home",
];
