// ignore-paths.js
// ---------------------------------------------------------------------------
// URL path PREFIXES to skip crawling (ALL lowercase, ALWAYS start with a slash).
// We’re filtering out auth, account, legal, marketing/PR, CMS/admin, search,
// feeds, generic help/FAQ, and other clearly non-directory sections.
// Keep these as *prefix* strings (no regex). Order doesn’t matter.
// Add carefully—avoid nuking potential directories like “/directory”, “/members”, etc.
// ---------------------------------------------------------------------------

export default [
	// --- Auth / Accounts / Profiles ---
	"/login",
	"/logout",
	"/signin",
	"/sign-in",
	"/signup",
	"/sign-up",
	"/register",
	"/registration",
	"/auth",
	"/sso",
	"/oauth",
	"/account",
	"/my-account",
	"/user",
	"/users",
	"/profile",
	"/profiles",
	"/settings",
	"/preferences",
	"/password",
	"/reset-password",
	"/two-factor",
	"/2fa",

	// --- Admin / CMS / System / API ---
	"/wp-admin",
	"/wp-login",
	"/wp-json",
	"/admin",
	"/administrator",
	"/backend",
	"/backoffice",
	"/umbraco",
	"/typo3",
	"/drupal",
	"/cms",
	"/system",
	"/dashboard",
	"/graphql",
	"/api",
	"/api-docs",
	"/openapi",
	"/swagger",

	// --- Legal / Privacy / Compliance ---
	"/privacy",
	"/privacy-policy",
	"/cookies",
	"/cookie",
	"/cookie-policy",
	"/terms",
	"/terms-of-use",
	"/terms-and-conditions",
	"/legal",
	"/legal-notice",
	"/imprint",
	"/impressum",
	"/disclaimer",
	"/compliance",
	"/gdpr",
	"/ccpa",
	"/accessibility",
	"/accessibility-statement",

	// --- Marketing / PR / Newsroom ---
	"/blog",
	"/news",
	"/press",
	"/press-releases",
	"/media",
	"/media-centre",
	"/media-center",
	"/newsroom",
	"/stories",
	"/highlights",
	"/announcements",
	"/updates",
	"/events",
	"/event",
	"/webinars",
	"/workshops",
	"/campaigns",
	"/case-studies",

	// --- Careers / HR / Investor Relations ---
	"/careers",
	"/jobs",
	"/job",
	"/vacancies",
	"/opportunities",
	"/internships",
	"/graduates",
	"/investors",
	"/investor-relations",
	"/ir",
	"/financials",
	"/reports", // (annual/impact reports—rarely brand directories)

	// --- E-commerce / Cart / Checkout ---
	"/cart",
	"/basket",
	"/checkout",
	"/order",
	"/orders",
	"/account/orders",
	"/payments",
	"/payment",
	"/billing",
	"/invoices",
	"/quote",
	"/quotes",

	// --- Store / Product Catalog (not brand/member directories) ---
	"/store",
	"/stores",
	"/shop",
	"/shops",
	"/product",
	"/products",
	"/catalog",
	"/catalogue",
	"/collections",
	"/find-product",
	"/where-to-buy",
	"/buy",

	// --- Generic Help / Support / Contact ---
	"/help",
	"/support",
	"/contact",
	"/contact-us",
	"/get-in-touch",
	"/faq",
	"/faqs",
	"/knowledge-base",
	"/kb",
	"/docs",
	"/documentation",
	"/resources",
	"/resource",
	"/downloads",
	"/download",

	// --- Search / Tags / Categories / Filters / Pagination shells ---
	"/search",
	"/search-results",
	"/tag",
	"/tags",
	"/category",
	"/categories",
	"/filter",
	"/filters",
	"/sort",
	"/archive",
	"/archives",

	// --- Feeds / Sitemaps / Robots ---
	"/feed",
	"/feeds",
	"/rss",
	"/atom",
	"/sitemap",
	"/sitemap.xml",
	"/robots.txt",

	// --- Misc public pages that aren’t org directories ---
	"/glossary",
	"/library",
	"/brand-assets",
	"/media-kit",
	"/donate",
	"/donation",
	"/volunteer",
	"/sponsor",
	"/sponsorship",

	// --- Status / Errors / Maintenance ---
	"/status",
	"/maintenance",
	"/under-maintenance",
	"/maintenance-mode",
	"/404",
	"/401",
	"/403",
	"/500",

	// --- Duplicates trimmed (keep once) ---
	// (Intentionally deduped vs your original paste.)
];
