// noise-topics.js
// ---------------------------------------------------------------------------
// Non-company nouns / regimes / standards commonly misread as org names.
// Keep EVERYTHING lowercase. Exact full-string match after normalization.
// Add ruthlessly whenever you see standards/frameworks leaking in results.
// ---------------------------------------------------------------------------

export default [
	// --- Governance / impact frameworks ---
	"community development funds",
	"impact management system",
	"impact assessment",
	"materiality assessment",
	"double materiality",
	"theory of change",
	"stakeholder engagement",
	"sustainable livelihoods",
	"just transition",
	"human rights due diligence",
	"supply chain due diligence",
	"responsible sourcing",
	"ethical procurement",
	"producer responsibility",
	"extended producer responsibility",
	"circular economy",
	"life cycle assessment",
	"environmental product declaration",
	"product category rules",
	"preferred by nature standard",

	// --- Generic roles / actors (not orgs) ---
	"producer",
	"producers",
	"consumer",
	"consumers",
	"business",
	"businesses",
	"retailers",
	"suppliers",
	"distributors",
	"vendors",
	"licensees",
	"members",
	"participants",
	"applicants",
	"auditees",

	// --- Reports / boilerplate docs ---
	"annual report",
	"impact report",
	"sustainability report",
	"esg report",
	"audit report",
	"assurance statement",
	"management statement",
	"policy statement",
	"code of conduct",
	"supplier code of conduct",
	"environmental policy",
	"social policy",
	"governance policy",
	"anti bribery policy",
	"modern slavery statement",

	// --- Compliance regimes / regulations / directives ---
	"cpsia",
	"reach",
	"rohs",
	"prop 65",
	"tsca",
	"recycled claim standard",
	"conflict minerals rule",
	"eu taxonomy",
	"csrd",
	"nfrd",
	"sfas",
	"oeko-tex standard 100",
	"oeko-tex leather standard",
	"oeko-tex made in green",
	"gots standard",
	"grs standard",
	"rws standard",
	"rds standard",
	"bluesign criteria",
	"cradle to cradle certified",
	"b corp certification",
	"fsc chain of custody",
	"pefc chain of custody",
	"fairtrade standard",
	"fair trade certified label",
	"sa8000 standard",
	"iso 9001",
	"iso 14001",
	"iso 14040",
	"iso 14044",
	"iso 20400",
	"iso 26000",
	"iso 45001",
	"iso 50001",
	"ohsas 18001",
	"sedex smeta",
	"higg index",
	"zdhc mrsl",
	"zdhc wastewater guidelines",
	"leeds", // common misspelling of leed (program, not a company)
	"leed",
	"breeam",
	"well building standard",
	"living building challenge",
	"declare label",
	"ecovadis rating",
	"un global compact",
	"sdgs", // sustainable development goals

	// --- Chemicals / hazard lists / databases ---
	"echa-svhc candidate list",
	"candidate list of svhc",
	"svhc",
	"ghs classification",
	"clp regulation",
	"tds",
	"sds",
	"msds",
	"hazardous substances list",

	// --- Sector-specific program names / schemes ---
	"factory production standard",
	"good manufacturing practice",
	"gmp",
	"capture fisheries standard",
	"aquaculture stewardship",
	"marine stewardship standard",
	"responsible down standard",
	"responsible wool standard",
	"responsible leather standard",
	"organic content standard",
	"recycled claim standard",
	"recycled content standard",

	// --- Auditing / verification terminology ---
	"third party verification",
	"independent verification",
	"chain of custody",
	"traceability program",
	"due diligence program",
	"risk assessment framework",
	"corrective action plan",
	"non conformity report",

	// --- Marketplace / pricing tools (not orgs) ---
	"prices and premiums",
	"price calculator",
	"premium calculator",
	"fee schedule",
	"licensing fees",

	// --- Donations / appeals / non-org CTAs we saw leaking ---
	"donate today",
	"donation form",
	"fundraising campaign",

	// --- Environment / generic policy nouns (not orgs) ---
	"environmental protection",
	"biodiversity strategy",
	"deforestation policy",
	"no deforestation",
	"no peat",
	"no exploitation",
	"climate neutrality",
	"net zero target",
	"science based targets",
	"scope 1 emissions",
	"scope 2 emissions",
	"scope 3 emissions",

	// --- Trade / certification program placeholders ---
	"trade standard",
	"certified farms",
	"farm certification",
	"group certification",
	"license management system",
	"certificate search",
	"certificate status",
	"certificate lookup",

	// --- Random UI-ish nouns that looked like entities in scraped pages ---
	"brand directory",
	"company directory",
	"member directory",
	"approved companies",
	"approved brands",
	"brand owners",
	"license holders",
	"participant list",
	"registration list",

	// --- Your originals to keep (for completeness) ---
	"community development funds",
	"impact management system",
	"theory of change",
	"annual report",
	"philanthropy",
	"producer",
	"consumer",
	"business",
	"environmental protection",
	"sustainable livelihoods",
	"cpsia",
	"reach",
	"echa-svhc candidate list",
	"iseal code compliant",
	"fair trade certified label",
	"factory production standard",
	"capture fisheries standard",
	"trade standard",
	"certified farms",
	"prices and premiums",
	"donate today",
];
