// Auto-generated from https://www.ecolabelindex.com/ecolabels/
// Run date: 2025-11-14T00:00:32.340Z

export const ECO_LABELS = [
  "4C Association",
  "80 PLUS",
  "AB (Agriculture Biologique)",
  "ABIO",
  "ABNT Ecolabel",
  "AENOR Medio Ambiente",
  "AfOR Compost Certified",
  "Afrisco Certified Organic",
  "AIAB (Italian Association for Organic Agriculture)",
  "AISE Charter for Sustainable Cleaning",
  "AMA Biozeichen",
  "American Grassfed",
  "ANAB - Architettura Naturale",
  "Animal Welfare Approved",
  "Aquaculture Stewardship Council",
  "Arge TQ",
  "AsureQuality Organic Standard",
  "Audubon International",
  "Australian Certified Organic",
  "Australian Forest Certification Scheme",
  "AvoGreen®",
  "B Corporation",
  "BASF Eco-Efficiency",
  "BASS (Product inventory for the construction industry)",
  "BASTA",
  "Bay Area Green Business",
  "Beluga",
  "Best Aquaculture Practices",
  "Better Cotton Initiative",
  "Better Environmental Sustainability Targets (BEST) Standard 1001",
  "BIO Hellas",
  "BIO Hotels",
  "Bio Quebec",
  "Bio Suisse",
  "Bio-Siegel",
  "BIODAR",
  "BioForum Biogarantie and Ecogarantie",
  "BioGro New Zealand",
  "Biokreis",
  "Bioland",
  "Bird Friendly Coffee",
  "Blue Angel",
  "Blue Flag",
  "bluesign® standard",
  "BMP Certified Cotton",
  "BOMA Go Green - BOMA BESt",
  "Bonsucro",
  "BRE Global Certified Environmental Profile",
  "BREEAM",
  "British Allergy Foundation Seal of Approval",
  "British Columbia Certified Organic",
  "Built Green",
  "Bundesverband Deutscher Fertigbau (BDF)",
  "Burn Wise EPA",
  "Byggvarubedömningen",
  "C.A.F.E. Practices",
  "Calidad Galapagos",
  "California Certified Organic Farmers - CCOF",
  "Canada Organic",
  "Canadian Certified Environmental Professional",
  "Carbon Care Certification",
  "Carbon Footprint of Products",
  "Carbon Neutral Certification",
  "Carbon Neutral Product Certification",
  "Carbon Reduction Label",
  "Carbon Trust Standard",
  "CarbonCare",
  "CarbonFree® Certified",
  "CarbonNeutral",
  "carboNZero",
  "Carrefour Eco-Planete",
  "CASBEE",
  "CEMARS (Certified Emissions Measurement and Reduction Scheme)",
  "Cerflor Forest Certification Programme: Brazil",
  "Certfor",
  "Certified Australian Southern Rocklobster \"CleanGreen\" Program",
  "Certified Envirodesic",
  "Certified Green Dealer",
  "Certified Green Restaurant®",
  "Certified Humane Raised and Handled",
  "Certified Natural Cosmetics",
  "Certified Naturally Grown",
  "Certified Pesticide Residue Free",
  "Certified Vegan",
  "Certified Wildlife Friendly®",
  "Certipur",
  "CertiPUR-US",
  "Chão Vivo",
  "China Energy Conservation Program (CECP)",
  "China Energy Label",
  "China Environmental Labelling",
  "China Organic Food Certification",
  "China Water Conservation Certification",
  "CHPS - Collaborative for High Performance Schools",
  "Clean Marine Green Leaf Eco-Rating Program",
  "Cleaner and Greener Certification",
  "Cleaning Industry Management Standard (CIMS)",
  "Climate Change Action",
  "Climate Neutral Certified",
  "Climate Registered",
  "Climatop",
  "CNET Asia Green Tag",
  "Compost Label RAL",
  "Compostability Mark of European Bioplastics",
  "Compostable: Biodegradable Products Institute Label",
  "Coop Naturaline: Switzerland",
  "Cotton Made in Africa",
  "Cradle to Cradle Certified(CM) Products Program",
  "CRI Green Label",
  "CSA Sustainable Forest Management",
  "CSRR Quality Standard",
  "Danish Indoor Climate Label",
  "Danish Ø-mark",
  "David Bellamy Conservation Award",
  "Declare",
  "Degree of Green®",
  "Delinat Bio Garantie",
  "Demeter Biodynamic®",
  "Deutsches Güteband Wein (DLG)",
  "DGNB Certificate",
  "DIN-Geprüft",
  "Dolphin Safe / Dolphin Friendly",
  "DUBOkeur",
  "e-Stewards Certification",
  "Earth Advantage",
  "EarthCheck",
  "EarthRight Business Certification",
  "Earthsure",
  "ECMA-370 - The Eco Declaration",
  "ECO certification",
  "Eco Warranty",
  "eco-INSTITUT-Label",
  "Eco-Leaf",
  "Eco-Living seal",
  "Eco-Rail Mark",
  "Eco-Schools",
  "Eco3Home",
  "EcoBroker",
  "Ecocert",
  "EcoLabel Luxembourg",
  "ECOLOGO",
  "EcoMark Africa",
  "Ecomark: India",
  "EcoMark: Japan",
  "EcoMaterial",
  "ECOproduct",
  "Ecoproof",
  "EcoStandard EcoProduct South Africa",
  "EcoVillage",
  "Effinature",
  "EKOenergy",
  "Ekolabel: Indonesia",
  "Ekologicky setrny vyrobek / Environmentally Friendly Product",
  "EMAS: European Eco-Management and Audit Scheme",
  "Emblem of Guarantee of Environmental Quality: Catalonia",
  "EnerGuide for Appliances",
  "EnerGuide Rating System (New Homes)",
  "Energy Label, Taiwan, ROC",
  "Energy Labelling of Buildings: EU",
  "Energy Rating Programme: Australia",
  "Energy Saving Labeling Program: Japan",
  "Energy Saving Recommended",
  "ENERGY STAR: Canada",
  "ENERGY STAR: New Zealand",
  "ENERGY STAR: USA",
  "Enviro-Mark®",
  "Environmental Choice New Zealand",
  "Environmental Product Declaration",
  "Environmental Warrant of Fitness",
  "Environmentally Friendly Label: Croatia",
  "Environmentally Preferable Product (EPP) Downstream",
  "EnviroStars",
  "EPA Lead-Safe Certification",
  "EPA SmartWay",
  "EPEAT",
  "Equitable Origin Certified",
  "EQUITRADE",
  "Estonian Ecotourism Quality Label",
  "Estonian Organic Farming",
  "Ethibel",
  "Etichetta ambientale",
  "EU Ecolabel",
  "EU Energy Label",
  "EU organic products label",
  "European Computer Manufacturers Association ECMA: TR/70",
  "European Green",
  "Fair Flowers Fair Plants",
  "Fair for Life",
  "Fair Labor Practices and Community Benefits",
  "Fair Trade Certified",
  "Fair Trade Organization Mark",
  "Fairtrade",
  "FairWertung",
  "FairWild",
  "Farm and Ranch Certification Program",
  "Farm Verified Organic",
  "FedEx EarthSmart Solutions",
  "Florimark",
  "Florverde Sustainable Flowers",
  "Flower Label Program (FLP)",
  "Fly-360-Green",
  "Flybe Aircraft Ecolabel",
  "Food Alliance Certified",
  "Forest Garden Products",
  "Forest Stewardship Council (FSC) Chain of Custody Certification",
  "Forest Stewardship Council® (FSC) Forest Management Certification",
  "Friend of the Sea",
  "Fuel Consumption Label: Australia",
  "Future Friendly - Proctor and Gamble",
  "GEO Certified",
  "GEV-Emicode",
  "Global Good Agricultural Practice (GAP)",
  "Global GreenTag Certified",
  "Global Organic Textile Standard",
  "Global Recycle Standard",
  "Gold Standard",
  "Good Environmental Choice \"Bra Miljöval\"",
  "Good Environmental Choice Australia (GECA)",
  "Good Shopping Guide Ethical Award",
  "GoodWeave",
  "Green Advantage Certification",
  "Green America's Green Business Certification",
  "Green Business Bureau",
  "Green Business League Certification",
  "Green C",
  "Green Certificate: Latvia",
  "Green Certified Site",
  "Green Choice: Phillipines",
  "Green Crane: Ukraine",
  "Green Dot / Der Grüner Punkt / Grønt Punkt",
  "Green Flag Program",
  "Green Globe Certification",
  "Green Globes",
  "Green Good Housekeeping Seal",
  "Green IT",
  "Green Key",
  "Green Key Eco-Rating Program",
  "Green Label: Israel",
  "Green Leaf Eco Standard",
  "Green Mark",
  "Green Office Champions: Seal of Good Practice",
  "Green Power Australia",
  "Green Products Standard",
  "Green Range",
  "Green Seal",
  "Green Shape",
  "Green Shield Certified",
  "Green Star Hotel Certification Programme",
  "Green Star NZ",
  "Green Table",
  "Green Tick",
  "Green Tourism Business Scheme",
  "Green-e Climate",
  "Green-e Energy",
  "Green-e Marketplace",
  "GreenCircle",
  "Greener Product Certification Seal",
  "GREENGUARD",
  "Greenline Print",
  "Greenlist - SC Johnson",
  "GreenPla",
  "Greenspec PASS",
  "GreenSure - Sherwin Williams",
  "GUT",
  "HAND IN HAND",
  "Healthy Child Healthy World",
  "Help build this site | Submit, suggest",
  "HKN NEU100",
  "Home Depot Eco Options",
  "Hong Kong Eco-label",
  "Hong Kong Green Label (HKGLS)",
  "HQE",
  "Hungarian Ecolabel / Környezetbarát Termék Védjegy",
  "ibex fairstay",
  "IBO",
  "IBU Type III Environmental Declaration (IBU Environmental Product Declaration)",
  "ICMA EcoLabel Standard Program",
  "IMO Certified",
  "India Organic - National Programme for Organic Production (NPOP)",
  "Indoor Air Comfort",
  "Indoor airPLUS",
  "International Eco Certification Program",
  "International Organic and Natural Cosmetics Corporation BDIH Standard",
  "IPM Star",
  "Japanese Agricultural Organic Standard (JAS)",
  "Just",
  "Keep up to date | News, press",
  "Korean Ecolabel",
  "Krav",
  "Label STEP",
  "Lao Organic",
  "LEAF",
  "LEAF Marque",
  "Leaping Bunny",
  "LEED Green Building Rating Systems",
  "LEED Professional Credentials",
  "Legambiente Turismo",
  "Lembaga Indonesia Ekolabel",
  "level",
  "LFP Certified",
  "LIFE Certification",
  "LIVE (Low Input Viticulture and Enology)",
  "LowCO2 Certification",
  "Luomu Sun Sign",
  "Luomuliitto - The Ladybird label",
  "M-BRIO Organic and Food Labeling",
  "M1 Emission Classification of Building Materials",
  "Marine Aquarium Council (MAC) Certification",
  "Marine Stewardship Council",
  "MAS Certified Green",
  "Max Havelaar",
  "Migros ECO",
  "Milieukeur: the Dutch environmental quality label",
  "Minergie",
  "Minergie-A",
  "Minergie-ECO",
  "Minergie-P",
  "NAHB Certified Green Professional",
  "NAHB Green",
  "National Carbon Offset Standard",
  "National Programme of Environmental Assessment and Ecolabelling in the Slovak Republik (NPEHOV)",
  "Nationwide House Energy Rating Scheme",
  "Natrue-Label",
  "Naturally Sephora",
  "Nature's Best Ecotourism",
  "Nature's Promise",
  "Naturemade",
  "natureplus",
  "Naturland e.V.",
  "NATURTEXTIL Best",
  "Neuland",
  "NF-Environnement Mark",
  "Nike Considered Design",
  "NoCO2",
  "Non-GMO",
  "Nordic Ecolabel or \"Swan\"",
  "NPA Natural Seal",
  "NSF Sustainability Certified Product",
  "NSF/ANSI 140 Sustainability Assessment for Carpet",
  "NSF/ANSI 332 Sustainability Assessment for Resilient Floor Coverings",
  "NSF/ANSI 336: Sustainability Assessment for Commercial Furnishings Fabric",
  "NSF/ANSI 342 Sustainability Assessment for Wallcovering Products",
  "Ø-label: Norway",
  "Ocean Wise",
  "OE-100 & OE-Blended",
  "Oeko-Tex Standard 100",
  "OK biobased",
  "OK biodegradable SOIL",
  "OK biodegradable WATER",
  "OK Compost",
  "OK Compost HOME",
  "OK Power",
  "ÖkoControl",
  "ÖkoPLUS",
  "On-Pack Recycling Label",
  "ORC-Cert Organic Seal",
  "Oregon Tilth",
  "Organic Content Standard (OCS)",
  "Organic Farmers & Growers Certification",
  "Organic Food China",
  "Organic Food Federation",
  "Österreichisches Umweltzeichen (Austrian Ecolabel)",
  "Paper Profile",
  "Passivhaus",
  "Per il Clima",
  "Phillips Green Logo",
  "Planet Positive",
  "Preservando El Medio Ambiente (Preserving the Environment)",
  "Processed Chlorine Free",
  "Programme for the Endorsement of Forest Certification (PEFC) schemes",
  "Protected Harvest",
  "QCS Organic",
  "R-2000 Certificate",
  "R2/RIOS Certified Electronics Recycler",
  "Rainforest Alliance Certified",
  "Recognised",
  "RECS International Quality Standard",
  "Recycled Content",
  "RenewablePLUS",
  "Rhode Island Certified Organic",
  "Roundtable on Sustainable Biomaterials",
  "RSPO Certified Sustainable Palm Oil",
  "RTRS Certified Soy",
  "Safe Agri-Food Product",
  "Salmon-Safe",
  "SCS Certified Biodegradable",
  "SCS FloorScore®",
  "SCS Indoor Advantage",
  "SCS Recycled Content",
  "SCS Sustainable Choice",
  "SeaChoice",
  "Seafood Safe",
  "SEE What You Are Buying Into",
  "SFC Member Seal",
  "Shipping Efficiency - A to G GHG Emission Rating",
  "Singapore Green Label Scheme (SGLS)",
  "SIP Certified",
  "SIRIM Certified",
  "Skal Eko Symbol",
  "SMaRT Consensus Sustainable Product Standards",
  "Smart WaterMark",
  "Soil Association Organic Standard",
  "Sourcemap",
  "Spiel Gut",
  "STARS",
  "State of Utah Organic Certification Program",
  "Stemilt Responsible Choice",
  "SundaHus Miljödata",
  "Sustainable Agricultural Network",
  "Sustainable Forestry Initiative (SFI)",
  "Sustainable Green Printing Partnership",
  "Sustainable Tourism Education Program (STEP)",
  "Sustainable Winegrowing New Zealand",
  "SustentaX",
  "Swiss Q-label",
  "TCO Certified",
  "TerraCycle",
  "Texas Certified Organically Produced",
  "Thai Green Label",
  "Timberland Green Index",
  "Totally Chlorine Free",
  "TRA Certification – Green Modular and Manufactured Homes",
  "TRA Certification – Green Recreational Vehicles (RVs)",
  "Tunisia Ecolabel",
  "TÜV Rheinland Certified",
  "TÜV SÜD Mark EE01/EE02",
  "U.S. EPA Safer Choice",
  "UK Fuel Economy Label",
  "UL Energy Efficiency Verified",
  "UL Environment Multi-Attribute Certification",
  "UL Environmental Claim Validation",
  "Umwelt-Etikette",
  "UPS Carbon Neutral",
  "UPS Eco Responsible Packaging Program",
  "US Composting Council Seal of Testing Assurance",
  "USDA Certified BioBased",
  "USDA Organic",
  "UTZ Certified",
  "Verified Carbon Standard",
  "VeriFlora",
  "Vermont Organic Certified",
  "Viabono",
  "Vitality Leaf",
  "Water Efficiency Labelling & Standards (WELS) Scheme",
  "Water Efficiency Product Labelling Scheme",
  "Water Lily: Lithuania",
  "WaterSense",
  "Waterwise Marque",
  "Whole Trade™ Guarantee",
  "Wholesome Food Association",
  "Wildlife Habitat Conservation Certification",
  "WindMade",
  "Windows Energy Rating Scheme (WERS)",
  "Woodnet Forest Certification Scheme: Belgium",
  "WQA Gold Seal",
  "WQA Sustainability Mark",
  "WSDA Organic",
  "ZQ Natural Fibre",
];
