/** @format */
// Sections to remove from pages before scraping text (CSS selectors)
export default [
	"header",
	"nav",
	"footer",
	"aside",
	"[role='navigation']",
	"[aria-label='breadcrumb']",
	".cookie",
	"#cookie",
	"[id*='cookie']",
	".banner",
	".hero",
	".promo",
	".newsletter",
	".subscribe",
	".modal",
	".drawer",
	".popup",
	"[aria-modal='true']",
	".breadcrumbs",
	".bread-crumbs",
	".toolbar",
	".topbar",
	".sidebar",
	".bottom-bar",
	".site-search",
	".site-footer",
	".site-header",
];
